import type { APIRoute } from 'astro';
import { products, categories, absolute } from '../data/content';
import { BLOG_POSTS } from '../lib/blog';

/**
 * Hand-rolled rather than generated by an integration, so that the noindex
 * pages (thank-you, 404) are excluded by construction rather than by
 * remembering to filter them, and so priorities reflect the site's structure.
 */
export const GET: APIRoute = () => {
  const entries: { url: string; priority: string }[] = [
    { url: '/', priority: '1.0' },
    { url: '/products/', priority: '0.9' },
    { url: '/get-a-quote/', priority: '0.8' },
    { url: '/about-us/', priority: '0.5' },
    { url: '/contact-us/', priority: '0.6' },
    ...categories.map((c) => ({ url: c.url, priority: '0.8' })),
    ...products.map((p) => ({ url: p.url, priority: '0.7' })),
    { url: '/blog/', priority: '0.6' },
    ...BLOG_POSTS.map((b) => ({ url: b.url, priority: '0.6' })),
    { url: '/privacy-policy/', priority: '0.2' },
    { url: '/terms-conditions/', priority: '0.2' },
    { url: '/refund_returns/', priority: '0.2' },
  ];

  const body = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries
  .map((e) => `  <url>\n    <loc>${absolute(e.url)}</loc>\n    <priority>${e.priority}</priority>\n  </url>`)
  .join('\n')}
</urlset>
`;

  return new Response(body, {
    headers: { 'content-type': 'application/xml; charset=utf-8' },
  });
};
