/**
 * Typed access to the extracted WordPress content.
 *
 * The JSON under this directory is generated by `tools/extract.py` and is
 * never hand-edited — rerunning the extractor must always reproduce it. This
 * module is the only place that reads it, so the shape is asserted once here
 * rather than in every page.
 */
import productsJson from './products.json';
import categoriesJson from './categories.json';
import pagesJson from './pages.json';
import { SITE_URL } from './site';

export interface Faq {
  question: string;
  answer: string;
}

export interface SpecTable {
  headers: string[];
  rows: string[][];
  pairs: { label: string; value: string }[];
}

export interface ProductImage {
  src: string;
  file: string;
  alt: string;
  title: string;
}

interface RawProduct {
  id: string;
  slug: string;
  name: string;
  url: string;
  categories: string[];
  sku: string;
  price: string;
  currency: string;
  inStock: boolean;
  shortDescription: string;
  description: string;
  specs: SpecTable;
  faqs: Faq[];
  images: ProductImage[];
  seoTitle: string;
  seoDescription: string;
  focusKeyword: string;
  primaryCategory: string;
  words: number;
}

export interface Product extends RawProduct {
  /** Category display names, in the order WordPress stored them. */
  categoryNames: string[];
  /** The category used for breadcrumbs and "related" — Yoast's primary if set. */
  primary: CategoryRef | undefined;
  /** Short description with markup removed, for meta descriptions and schema. */
  plainShort: string;
}

export interface CategoryRef {
  slug: string;
  name: string;
  url: string;
}

interface RawCategory {
  slug: string;
  name: string;
  parent: string;
  parentName: string;
  url: string;
  description: string;
  products: string[];
}

export interface Category extends RawCategory {
  items: { name: string; url: string }[];
  metaDescription: string;
  parentRef: CategoryRef | undefined;
  children: CategoryRef[];
}

export interface SitePage {
  slug: string;
  title: string;
  url: string;
  html: string;
  seoTitle: string;
  seoDescription: string;
  hasElementor: boolean;
  words: number;
}

const strip = (h: string) =>
  h.replace(/<[^>]+>/g, ' ').replace(/&nbsp;/g, ' ').replace(/\s+/g, ' ').trim();

const rawCategories = categoriesJson as RawCategory[];
const rawProducts = productsJson as RawProduct[];

const refOf = (c: RawCategory): CategoryRef => ({ slug: c.slug, name: c.name, url: c.url });
const bySlug = new Map(rawCategories.map((c) => [c.slug, c]));

/**
 * WordPress stored the primary category as a term ID, which the export does not
 * resolve, so the first assigned category is used instead. Where a product sits
 * in a child category that child wins, because it is the more specific of the
 * two and is what the old breadcrumb showed.
 */
function primaryOf(p: RawProduct): RawCategory | undefined {
  const assigned = p.categories.map((s) => bySlug.get(s)).filter(Boolean) as RawCategory[];
  return assigned.find((c) => c.parent) ?? assigned[0];
}

export const products: Product[] = rawProducts.map((p) => {
  const primary = primaryOf(p);
  return {
    ...p,
    categoryNames: p.categories.map((s) => bySlug.get(s)?.name ?? s),
    primary: primary ? refOf(primary) : undefined,
    plainShort: strip(p.shortDescription),
  };
});

const productBySlug = new Map(products.map((p) => [p.slug, p]));

export const categories: Category[] = rawCategories.map((c) => {
  const items = c.products
    .map((s) => productBySlug.get(s))
    .filter(Boolean)
    .map((p) => ({ name: p!.name, url: p!.url }));
  const parent = c.parent ? bySlug.get(c.parent) : undefined;
  return {
    ...c,
    items,
    parentRef: parent ? refOf(parent) : undefined,
    children: rawCategories.filter((x) => x.parent === c.slug).map(refOf),
    metaDescription:
      strip(c.description) ||
      `Browse ${items.length} custom ${c.name.toLowerCase()} from Kraft Box Pack. ` +
        `Wholesale pricing, free design assistance and 8-10 business day turnaround.`,
  };
});

export const pages = pagesJson as SitePage[];

export const getProduct = (slug: string) => productBySlug.get(slug);
export const getCategory = (slug: string) => categories.find((c) => c.slug === slug);

/**
 * The products a category archive lists, including those that sit only in one
 * of its children.
 *
 * This is what WooCommerce did: the live "Kraft Gift & Specialty Boxes" page
 * listed products belonging to its "Custom Gift Boxes" child alongside its own,
 * so listing direct assignments only would drop links that exist today. It is
 * also the behaviour a visitor expects — a parent category that hides most of
 * its range is a dead end.
 */
export function productsIn(slug: string): Product[] {
  const descendants = new Set([slug]);
  for (const c of rawCategories) {
    if (c.parent && descendants.has(c.parent)) descendants.add(c.slug);
  }
  return products.filter((p) => p.categories.some((c) => descendants.has(c)));
}

/** Top-level categories, for the homepage and footer. */
export const topCategories = categories.filter((c) => !c.parent);

export const absolute = (path: string) => new URL(path, SITE_URL).href;

/**
 * Related products: others sharing a category, preferring the same primary one.
 *
 * The window rotates rather than always taking the first eight. Taking the head
 * of the list every time would give the alphabetically-early products in a
 * large category several inbound links each and the rest none, which is both a
 * worse experience and a measurable loss against the old site — WooCommerce
 * varied its selection, so those links existed. Starting each product at its
 * own offset spreads the links evenly across the category and keeps the result
 * deterministic, so a rebuild produces the same pages.
 */
export function relatedTo(p: Product, limit = 8): Product[] {
  const pool = products.filter(
    (x) => x.slug !== p.slug && x.categories.some((c) => p.categories.includes(c)),
  );
  const samePrimary = pool.filter((x) => x.primary?.slug === p.primary?.slug);
  const rest = pool.filter((x) => !samePrimary.includes(x));
  const ordered = [...samePrimary, ...rest];
  if (ordered.length <= limit) return ordered;

  const offset = ordered.findIndex((x) => x.slug > p.slug);
  const start = offset === -1 ? 0 : offset;
  return Array.from({ length: limit }, (_, i) => ordered[(start + i) % ordered.length]);
}
